spring:
  application:
    name: test
  profiles:
    active: dev   # 设置当前环境： dev  prod
  cloud:
    sentinel:
      transport:
        port: 8720 #跟sentinel控制台交流的端口,随意指定一个未使用的端口即可
        client-ip: localhost
        dashboard: localhost:8180 # 指定sentinel控制台地址。
      eager: true
      datasource:
        # 自定义命名
        flow-rule:
          # 支持多种持久化数据源：file、nacos、zk、apollo、redis、consul
          nacos:
            # naco服务地址
            server-addr: localhost:8001
            # 命名空间，根据环境配置
            namespace: dev
            # 这里我做了一下细分，不同规则设置不同groupId
            group-id: DEFAULT_GROUP
            # 仅支持JSON和XML类型
            data-id: ${spring.application.name}-sentinel-flow
            # 规则类型：flow、degrade、param-flow、system、authority
            rule-type: flow
      web-context-unify: false #默认将调用链路收敛
server:
  # 端口号
  port: 5050